### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by paulray** [ipta/pulsar-clock-corrections#1]
To make it easy for new users, I suggest the following:
* Add to the instructions a description of how to get download-clock-corrections.py (without cloning the whole repo), if that is all they want.  I did it like this:
```
https://raw.githubusercontent.com/ipta/pulsar-clock-corrections/main/download-clock-corrections.py
```
* Add this line to the beginning of download-clock-corrections.py, so it is runnable from the command line:
```
#!/usr/bin/env python
```

**Comment by aarchiba** [comment]
Good idea - you can also get it by clicking on various github stuff (as you clearly know) but that is not especially friendly.

**Comment by aarchiba** [comment]
Sorry for not noticing this - I'm not used to PRs and issues on this project yet!
