### ISSUE TITLE
BIPM only goes up to 2021, and may not be fully correct

### ISSUE THREAD

**Issue by dlakaplan** [ipta/pulsar-clock-corrections#10]
@vhaasteren noted:

> When running the `update_clock_corrections.py` script, I got a warning that `tai2tt_bipm2022.clk` was missing. Looking into it, it seems that `tai2tt_bipm2021.clk` and` tai2tt_bipm2020.clk` are actually copies of `tai2tt_bipm2019.clk`. I don't think that's supposed to happen? Or is it?

This may need a little deeper dive, since there is some confusion about those files.  But I think this can be fixed within this repo.

**Comment by dlakaplan** [comment]
@jorisverbiest

**Comment by vhaasteren** [comment]
The workaround I used in the Dockerfile that I was building at the time consisted of just copying `tai2tt_bipm2019.clk` to upcoming years, and letting `pulsar-clock-corrections` update it properly. It **seems** to work.

```
WORKDIR $SOFTWARE_DIR/pulsar-clock-corrections
RUN mkdir -p gh-pages/.this_is_gh_pages && \
    for year in $(seq 2022 $(( $(date +%Y) - 1 ))); do \
        cp T2runtime/clock/tai2tt_bipm2019.clk T2runtime/clock/tai2tt_bipm${year}.clk; \
    done
```

**Comment by dlakaplan** [comment]
Is https://www.bipm.org/en/time-ftp/tt-bipm- the correct source location?

**Comment by dlakaplan** [comment]
I am also a little confused because:
* the final dates in e.g., BIPM2021 is 2024-09-26 MJD 60579.0, but https://webtai.bipm.org/ftp/pub/tai/ttbipm/TTBIPM.2021 only goes up to 2021-12-31.   Probably this is because it adds prediction data to smooth out newer TOAs.  I think this follows lines like:
```
Until the next realization, users can extend TT(BIPM22) after MJD 59939 as
TT(BIPM22) = TAI + 32.184 s + 27670.6 ns - 0.01x(MJD-59939) ns 
```
and the header does say this, so maybe we just need to understand how these are computed.
* Separately, https://github.com/ipta/pulsar-clock-corrections/blob/main/bipm.py#L289 looks like it does try to get newer files but hasn't: maybe just because this hasn't been run since April?

**Comment by dlakaplan** [comment]
If I run it locally I do pull down BIPM2022 but other things fail because the file doesn't already exist and neither does a relevant log file.  If I copy in a stub then things run but I'm not sure all of the appropriate files are actually updated.

**Comment by dlakaplan** [comment]
I couldn't convince this to automatically update the file, but I was able to create the appropriate file using:
```
import bipm

bipm2022 = bipm.get_ttbipmxy_corrections_clock(2022)
bipm2022.write_tempo2_clock_file('tai2tt_bipm2022.clk')
```
Along with that there was a bug(?) in the code that made the top comment in BIPM 2020/2021/2022 all read BIPM 2019.

**Comment by dlakaplan** [comment]
And I also agree that BIPM2020 seemed to be the same as BIPM2021 (which looks OK).
