### ISSUE TITLE
No integration tests

### ISSUE THREAD

**Issue by dlakaplan** [ipta/pulsar-clock-corrections#13]
How to know if a PR is valid?  Should it maybe be forced to run the GH action (`update_clock_corrections.py`) with no errors?

**Comment by aarchiba** [comment]
That would probably do most of the required validation. Won't necessarily help with code changes, but it might.

**Comment by aarchiba** [comment]
Quick implementation of this. It would be sort of nice to check that the new version doesn't prevent any file from downloading/being included that was previously working, but that's tricky to even define.
