### ISSUE TITLE
Other issues

### ISSUE THREAD

**Issue by dlakaplan** [ipta/pulsar-clock-corrections#15]
When I run having merged in #11, #12 , #14 I still get some failures:
* GBT                  2023-12-04 18:55:06.819 - Validation failed: New version of tempo/clock/time_gbt.dat clock corrections differ from old version where they overlap in 11 places
* WSRT (TEMPO)         2023-12-04 18:55:15.887 - Validation failed: Unable to read new version of tempo/clock/time_wsrt.dat: Clock file /var/folders/_v/j_bk73y94jl2_xvhdb_lvvkc0000gr/T/astropy-download-74142-987ogcnw appears to be out of order
* Parkes (TEMPO)       2023-12-04 18:55:20.301 - Validation failed: Unable to read new version of tempo/clock/time_pks.dat: Clock file /var/folders/_v/j_bk73y94jl2_xvhdb_lvvkc0000gr/T/astropy-download-74142-cjeyp52_ appears to be out of order
* Meerkat (observatory) 2023-12-04 18:55:32.888 - Failed to download: <urlopen error _ssl.c:983: The handshake operation timed out>
* ~~Meerkat (TEMPO2)     2023-12-04 18:55:35.017 - Validation failed: New version of T2runtime/clock/mk2utc.clk MJDs differ from old version where they overlap in 597 places~~
* Nancay to obspm      2023-12-04 18:55:35.954 - Validation failed: New version of T2runtime/clock/ncyobs2obspm.clk has decreased from 19563 to 17671 measurements.
* ~~CHIME                2022-06-20 22:07:51.282 - No way to download: 'T2runtime/clock/chime2gps.clk'~~
* ~~GMRT                 2022-06-01 12:20:21.838 - Failed to download: HTTP Error 404: Not Found~~
* obspm                2023-12-04 18:55:36.397 - Validation failed: New version of T2runtime/clock/obspm2gps.clk has decreased from 6851 to 6426 measurements.

Resolutions:
* CHIME and GMRT are synced directly to GPS, so those entries are just placeholders and shouldn't work.  Maybe that should be made more clear.
* I don't know why MeerKAT Observatory is timing out.  I can get it locally.
* Force update of Meerkat (TEMPO2) (#12 )
* Others should be investigated separately:
  * `T2runtime/clock/obspm2gps.clk`, `T2runtime/clock/ncyobs2obspm.clk` errors have persisted for a while.  the Tempo2 versions may just be out of date
  * `tempo/clock/time_wsrt.dat` errors have persisted for a while.  The tempo version may be out of date
  * `tempo/clock/time_pks.dat` errors have persisted for a while.  The tempo version may be out of date

**Comment by aarchiba** [comment]
As of now:

- GBT works (note in description about awkward resolution)
- WSRT (TEMPO) is a problem in the file on sourceforge; bug report here anyway
- Parkes (TEMPO) is a problem in the file on sourceforge; bug report here anyway
- Meerkat is downloading fine
- Nancay seems fine
- obspm seems fine
- CHIME and GMRT have (null) in the name and an explanation

Does that cover everything?

**Comment by dlakaplan** [comment]
I think so.  Can probably close this.
