### ISSUE TITLE
time_ao.dat in tempo2 directory

### ISSUE THREAD

**Issue by tcromartie** [ipta/pulsar-clock-corrections#8]
Not super important, but here for posterity. It could be misleading to have the old version of time_ao.dat in the tempo2 runtime directory because it doesn't actually need it; it's an artifact that clashes with the version that's in the tempo directory. (The tempo2 version goes up to 2018, and the tempo version is up-to-date.)

**Comment by aarchiba** [comment]
Very sensible. I don't know what it was doing there, probably was in the T2Runtime directory when I cloned it.
